"""Tests for ``api/routers/pipeline.py``.

Each route is hit through ``TestClient``; replies are simulated by adding
matching events directly to the in-memory FakeRedis stream after the
request publishes its trigger.
"""
from __future__ import annotations

import asyncio
import json
import threading
import time
import uuid

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from api.middleware import bearer_auth
from api.routers import pipeline as pipeline_router
from tests._fakes import FakeRedis


@pytest.fixture(autouse=True)
def _disable_bearer(monkeypatch: pytest.MonkeyPatch):
    """Empty bearer disables auth in dev mode — except where overridden."""
    class _S:
        atlas_bearer_token = ""

    monkeypatch.setattr(bearer_auth, "get_settings", lambda: _S())


@pytest.fixture
def app_and_redis() -> tuple[FastAPI, FakeRedis]:
    app = FastAPI()
    redis = FakeRedis()
    app.state.redis = redis
    app.include_router(pipeline_router.router)
    return app, redis


def _seed_reply_after_publish(
    redis: FakeRedis,
    *,
    correlation_id: str,
    message_type: str,
    payload: dict | None = None,
) -> threading.Thread:
    """Push a synthetic reply event onto the stream from a side thread."""

    def _worker() -> None:
        # Wait briefly to let the route publish the trigger first.
        time.sleep(0.1)
        envelope = json.dumps(
            {
                "correlation_id": correlation_id,
                "message_type": message_type,
                "payload": payload or {},
            }
        )
        loop = asyncio.new_event_loop()
        try:
            loop.run_until_complete(redis.xadd("atlas:events", {"json": envelope}))
        finally:
            loop.close()

    t = threading.Thread(target=_worker, daemon=True)
    t.start()
    return t


def test_route_enforces_bearer_when_token_set(monkeypatch: pytest.MonkeyPatch) -> None:
    class _S:
        atlas_bearer_token = "abc"

    monkeypatch.setattr(bearer_auth, "get_settings", lambda: _S())
    app = FastAPI()
    app.state.redis = FakeRedis()
    app.include_router(pipeline_router.router)
    client = TestClient(app)
    res = client.post("/pipeline/oracle-scan", json={})
    assert res.status_code == 401


def test_oracle_scan_returns_envelope_on_reply(
    app_and_redis: tuple[FastAPI, FakeRedis],
) -> None:
    app, redis = app_and_redis
    # Pre-publish a reply with a correlation_id we'll observe via the route.
    # Since correlation_id is generated by the route when no signal_id supplied,
    # patch uuid.uuid4 to return a stable id.
    fixed = uuid.UUID("00000000-0000-0000-0000-0000000000aa")
    original_uuid = pipeline_router.uuid.uuid4
    pipeline_router.uuid.uuid4 = lambda: fixed  # type: ignore[assignment]
    try:
        _seed_reply_after_publish(
            redis,
            correlation_id=str(fixed),
            message_type="research_update",
            payload={"signals": []},
        )
        client = TestClient(app)
        res = client.post("/pipeline/oracle-scan", json={"top_n": 5})
        assert res.status_code == 200
        body = res.json()
        assert body["status"] == "ok"
        assert body["correlation_id"] == str(fixed)
        assert body["result"]["message_type"] == "research_update"
    finally:
        pipeline_router.uuid.uuid4 = original_uuid  # type: ignore[assignment]


def test_guardian_check_uses_signal_id_as_correlation(
    app_and_redis: tuple[FastAPI, FakeRedis],
) -> None:
    app, redis = app_and_redis
    sig = "sig-123"
    _seed_reply_after_publish(
        redis,
        correlation_id=sig,
        message_type="trade_approved",
        payload={"approved": True},
    )
    client = TestClient(app)
    res = client.post("/pipeline/guardian-check", json={"signal_id": sig})
    assert res.status_code == 200
    body = res.json()
    assert body["correlation_id"] == sig
    assert body["result"]["payload"]["approved"] is True


def test_trader_execute_validates_mode(app_and_redis: tuple[FastAPI, FakeRedis]) -> None:
    app, _ = app_and_redis
    client = TestClient(app)
    res = client.post(
        "/pipeline/trader-execute",
        json={"signal_id": "s-9", "mode": "wild"},
    )
    assert res.status_code == 422  # pydantic regex mismatch


def test_trader_execute_rejects_auto_live(
    app_and_redis: tuple[FastAPI, FakeRedis],
) -> None:
    """Live mode must never accept auto=True. Hard safety belt."""
    app, _ = app_and_redis
    client = TestClient(app)
    res = client.post(
        "/pipeline/trader-execute",
        json={"signal_id": "s-1", "mode": "live", "auto": True},
    )
    assert res.status_code == 403
    body = res.json()
    assert body["status"] == "rejected"
    assert body["reason"] == "live_requires_operator_confirmation"


def test_trader_execute_passes_auto_paper(
    app_and_redis: tuple[FastAPI, FakeRedis], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Paper + auto=True flows through the normal pipeline."""
    app, redis = app_and_redis
    monkeypatch.setattr(pipeline_router, "DEFAULT_TIMEOUT_SEC", 0.2)
    client = TestClient(app)
    res = client.post(
        "/pipeline/trader-execute",
        json={"signal_id": "s-2", "mode": "paper", "auto": True},
    )
    # Will time out since no reply seeded — but request itself must be accepted.
    assert res.status_code == 202
    msgs = redis._streams.get("atlas:events", [])
    assert msgs
    payload = json.loads(msgs[0][1]["json"])
    assert payload["payload"]["auto"] is True
    assert payload["payload"]["mode"] == "paper"


def test_sage_review_accepts_idempotency_key(
    app_and_redis: tuple[FastAPI, FakeRedis],
) -> None:
    app, redis = app_and_redis
    trade = "trade-x"
    _seed_reply_after_publish(
        redis,
        correlation_id=trade,
        message_type="learning_insight",
        payload={"summary": "ok"},
    )
    client = TestClient(app)
    key = str(uuid.uuid4())
    res1 = client.post(
        "/pipeline/sage-review",
        json={"trade_id": trade},
        headers={"X-Idempotency-Key": key},
    )
    assert res1.status_code == 200
    # Replay: cache hit → same body without needing a new reply.
    res2 = client.post(
        "/pipeline/sage-review",
        json={"trade_id": trade},
        headers={"X-Idempotency-Key": key},
    )
    assert res2.status_code == 200
    assert res2.json() == res1.json()


def test_pipeline_timeout_returns_202_with_job_id(
    app_and_redis: tuple[FastAPI, FakeRedis], monkeypatch: pytest.MonkeyPatch
) -> None:
    app, _ = app_and_redis
    # Force a tiny timeout so the test runs fast.
    monkeypatch.setattr(pipeline_router, "DEFAULT_TIMEOUT_SEC", 0.3)
    client = TestClient(app)
    res = client.post("/pipeline/architect-rank", json={"candidates": []})
    assert res.status_code == 202
    body = res.json()
    assert body["status"] == "timeout"
    assert body["job_id"] == body["correlation_id"]


def test_oracle_scan_publishes_to_stream(
    app_and_redis: tuple[FastAPI, FakeRedis], monkeypatch: pytest.MonkeyPatch
) -> None:
    app, redis = app_and_redis
    monkeypatch.setattr(pipeline_router, "DEFAULT_TIMEOUT_SEC", 0.2)
    client = TestClient(app)
    client.post("/pipeline/oracle-scan", json={})
    msgs = redis._streams.get("atlas:events", [])
    assert msgs, "expected the route to xadd a trigger"
    payload = json.loads(msgs[0][1]["json"])
    assert payload["target_agent"] == "oracle"
    assert payload["message_type"] == "user_command"
